### PR TITLE
Add Swedish translation

### PR DESCRIPTION
**Pull request by Djhg2000**
I translated the web interface to Swedish and tested it on my printer. While doing so I was unable to locate a few strings (such as where 't="Maintenance"' is located) but to my knowledge the translations should be correct in every relevant context.

### CODE REVIEW

**Comment by Djhg2000** [comment]
I'm confused. I'm running the latest git version, shouldn't I see those strings in the UI?

**Comment by chrishamm** [comment]
PRouzeau is right, see https://github.com/chrishamm/DuetWebControl/blob/master/language.xml#L325
Djhg2000, please add the missing entries as seen in the link above and I'll merge in your changes when I get a chance.

The translations aren't yet complete for all languages, but I'm hoping to get them updated until I release v1.08.

**Comment by Djhg2000** [comment]
Oh I see now, I copied the Spanish translation as a template. Will fix ASAP!

**Comment by Djhg2000** [comment]
Translations updated for 1.07

**Comment by Djhg2000** [comment]
While poking around in the interface I came up with better translations in a few places and pushed those to my fork as well.

**Comment by chrishamm** [comment]
Thanks, I've merged them into v1.08

**Pull request closed without merging**
