### PR TITLE
Adding ability to index macro directories.

### PR DESCRIPTION
**Pull request by eduardoscamargo**
It is possible to prepend number followed by "_" to macro directories, like:

- 0_Tunning
- 1_Probe
- 2_Aux

DWV will sort the directories the same way it does for filenames and remove the prefix from directories names. Actually, as you can see, it uses the same strip function that is used for files.

### CODE REVIEW

**Comment by eduardoscamargo** [comment]
Is there any problem with this PR? Anyway I should improve it?

**Comment by Patrik-svobodik** [comment]
I think the problem is that it is for DWC1 if I am not mistaken, @chrishamm
wants to fully focus on DWC2

čt 11. 4. 2019 v 17:43 odesílatel Eduardo de Camargo <
notifications@github.com> napsal:

**Comment by chrishamm** [comment]
I'll probably release a final version of DWC1 and when I do I will get back to your PR. Sorry if this takes a bit longer but I'm fully tied up with work that I have to finish by the end of this month.

**Comment by eduardoscamargo** [comment]
No problem. It is my first time helping here, só I just wanted to be sure that was correct. Thanks! Great work btw!

**Pull request closed without merging**
